---
title: "EDW: dBeaver Setup"
date: "Updated 05/Jan/2023"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{EDW: dBeaver Setup}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

[dBeaver Community](https://dbeaver.io) is a 

> "free multi-platform [macOS, Windows, Linux, there is even an Eclipse plugin] database tool for developers, database administrators, analysts and all people who need to work with databases" that "supports all popular databases: MySQL, PostgreSQL, SQLite, Oracle, DB2, SQL Server, Sybase, MS Access, Teradata, Firebird, Apache Hive, Phoenix, Presto, etc."

## Download & Install

 - Visit [https://dbeaver.io](https://dbeaver.io) and click the "Download" button.
 - Install dBeaver following the instructions at [https://dbeaver.io/download/](https://dbeaver.io/download/). For macOS users, in addition to the standard dmg files there are [Brew Cask](https://formulae.brew.sh/cask/dbeaver-community) and [MacPorts](https://ports.macports.org/port/dbeaver-community/summary/).


## Setup dBeaver

select "Oracle" SQL database

set host as: ebsprd390d.ais.msu.edu

set database: MSUEDW.EBSP.MSU.EDU

set port: 1521

authentication: "oracle database native"

username: your NetID

password: password from dataservices

click "save password"

click save

