---
title: "PAG: About"
date: "Updated 04/Oct/2022"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PAG: About}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Welcome to the official webpages of the unofficial Predictive Analytics Group (PAG)! We work within the [Associate Provost Office of Enrollment and Academic Strategic Planning](https://esp.msu.edu) at [Michigan State University](https://www.msu.edu). 

Our work is at the intersection of potential and current students' data to ask and answer questions about potential students' behaviors and outcomes. Using our combined expertise in economics, analytics, and predictive modelling, we provide a unique perspective on student-centric quandaries. Currently, we are studying economic mobility and gaining a deeper understanding of applicants.

We believe in creating and fostering a supportive and inclusive environment for our members to thrive and advance their career. To support our efforts, we developed and adopted an evolving collection of [Guidelines & Policies](PAG_GuidelinesAndPolicies.Rmd) and [prompts about how each of us likes to be mentored](PAG_HowILikeToBeMentored.Rmd).


## Current Members

We believe a small group with a diverse collection of viewpoints and experiences is the optimal way to approach many types of research questions. 

**Seth Tanner Walker**: Seth is a Graduate Student in the [Department of Economics](https://econ.msu.edu/) in the [College of Social Science](https://socialscience.msu.edu/) working towards a Ph.D. in xxxx. Seth is exploring the impact of the [Spartan Advantage program](https://finaid.msu.edu/spad.asp). Seth earned dual Bachelors degrees from [James Madison University](https://www.jmu.edu) in Quantitative Economics & Mathematics and Music Performance. [ [LinkedIn]() | [Website]() | [Social]() ]


**Steven R Miller**: Steve is an Assistant Professor in the [Department of Agricultural, Food, and Resource Economics](https://www.canr.msu.edu/afre/index) in the [College of Agriculture & Natural Resources](https://www.canr.msu.edu/) and specializes in applied economic methods for forecasting and impact analysis. Steve is also the Director of the [Center for Economic Analysis](https://www.canr.msu.edu/cea/). [ [LinkedIn](https://www.linkedin.com/in/steven-miller-3b5a546) | [Website]() | [Social]() ]


**Emilio Xavier Esposito**: Emilio is an Academic Specialist in the [Associate Provost Office of Enrollment and Academic Strategic Planning](https://esp.msu.edu) and explores novel ways student data relates to various outcomes. Emilio's background in early stage drug discovery, specifically computational chemistry and biochemistry. Emilio is also an Editor for the [Journal of Molecular Graphics and Modelling](https://www.sciencedirect.com/journal/journal-of-molecular-graphics-and-modelling). [ [LinkedIn](https://www.linkedin.com/in/emilioxavieresposito) | [Website](http://www.exeResearch.com) | [Twitter](https://twitter.com/exesposito) ]



## Group Meetings
While we focus on answering questions related to enrollment, we know an implied mission is assisting in the development of those that want to do similar work. To this end, we hold twice-a-week group meetings where we discuss

 - Relevant research articles
 - Application of function-specific applications
 - Examples of new (to us) coding methods
 - Our research success and setbacks

We invite and welcome those outside of our group to join our meetings. Please contact [Emilio](mailto:emilio@msu.edu?subject=I%20want%20to%20attend%20PAG%20group%20meetings!) for the Zoom link.


### Group Meeting Schedule

Group Meeting are on Tuesdays and Thursdays and we start at 3p and end between 4p and 4:30p. Our Group Meeting schedule is loose. Each meeting starts with a quick "stand-up" where everyone gets five minutes to briefly say...

  - what they are working on
  - one thing causing grief
  - one victory

| Week of the Month | Tuesday | Thursday |
|:-----------------:|:-------:|:--------:|
| 1st               | General | Emilio   |
| 2nd               | General | Steve    |
| 3rd               | General | Seth     |
| 4th               | General | Social   |

  - The **Tuesday "General" meetings** are a catch-all for coding demonstrations, help solving research and coding conundrums, guest speakers, and administrative and management discussions. 
  - The **Thursday meetings** are an opportunity for each group member (see schedule below) to present an aspect of their project. The fourth Thursday of each month allows the group to meet in-person for beverages and snacks if they can easily make it to -- or near -- campus. We also have the option to cancel the fourth Thursday meeting and make this decision during the fourth Tuesday meeting.

### Group Meeting Topics

  - 04/Oct/2022: How to compare Census Tract counts to Lat-Lon counts; Introduction to GitHub
  - 06/Oct/2022: Cleaning SLATE data (Emilio)
  - 11/Oct/2022:
  - 13/Oct/2022: (Steve)
  - 18/Oct/2022: 
  - 20/Oct/2022: (Seth)
  - 25/Oct/2022: 
  - 27/Oct/2022: (Social)
  - 01/Nov/2022:
  - 03/Nov/2022: (Emilio)
  - 08/Nov/2022:
  - 10/Nov/2022: (Steve)
  - 15/Nov/2022:
  - 17/Nov/2022: (Seth)
  - 22/Nov/2022:
  - 24/Nov/2022: Thanksgiving! No meeting
  - 29/Nov/2022: (Social)
  - 01/Dec/2022: (Emilio)
  - 06/Dec/2022: 
  - 08/Dec/2022: (Steve)
  - 13/Dec/2022: 
  - 15/Dec/2022: (Seth)


