---
title: "PAG: Group Meetings"
date: "Updated 20/Jan/2023"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PAG: Group Meetings}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

While we focus on answering questions related to enrollment, we know an implied mission is assisting in the development of those that want to do similar work. To this end, we hold twice-a-week group meetings where we discuss

 - Relevant research articles
 - Application of function-specific applications
 - Examples of new (to us) coding methods
 - Our research success and setbacks

We invite and welcome those outside of our group to join our meetings. Please contact [Emilio](mailto:emilio@msu.edu?subject=I%20want%20to%20attend%20PAG%20group%20meetings!) for the Zoom link.


## Group Meeting Schedule

Group Meeting are on Tuesdays and Thursdays and we start at 3p and end between 4p and 4:30p. Our Group Meeting schedule is loose. Each meeting starts with a quick "stand-up" where everyone gets five minutes to briefly say...

  - what they are working on
  - one thing causing grief
  - one victory

| Week of the Month | Tuesday | Thursday |
|:-----------------:|:-------:|:--------:|
| 1st               | General | Emilio   |
| 2nd               | General | Steve    |
| 3rd               | General | Seth     |
| 4th               | General | Social   |

  - The **Tuesday "General" meetings** are a catch-all for coding demonstrations, help solving research and coding conundrums, guest speakers, and administrative and management discussions. 
  - The **Thursday meetings** are an opportunity for each group member (see schedule below) to present an aspect of their project.
  - We meet in person for [book club](#BookClub) discussion and these meetings take the place of a predetermined Thursday meeting. Check the meeting schedule below for when and where book club meets.
  
  <!-- The fourth Thursday of each month allows the group to meet in-person for beverages and snacks if they can easily make it to -- or near -- campus. We also have the option to cancel the fourth Thursday meeting and make this decision during the fourth Tuesday meeting. -->

## Group Meeting Topics

### Spring/2023 Meetings

  - 12/Jan/2023 (Thursday): Welcome back! Introduction to Asana.
  - 17/Jan/2023 (Tuesday):  Paper work, plans for the coming semester, and official start of the book club (see below).
  - 19/Jan/2023 (Thursday): Reading day
  - 24/Jan/2023 (Tuesday):  Introduction to the HPCC (Thank you Seth!)
  - 26/Jan/2023 (Thursday): (Re)Introduction to GitHub and [theHUB](https://theHopefulBox.com). The basics of writing R functions: 1. Make it work, 2. Make it clear, 3. Make it fast-ish. 
  - 31/Jan/2023 (Tuesday):  Cleaning up last year's code and making it reproducible.
  - 02/Feb/2023 (Thursday): [_**Book club**_](#BookClub) meeting! Meet at [Blue Owl Coffee in East Lansing](https://www.blueowlcoffee.net), [Google Map](https://goo.gl/maps/CVkykGhSUkkofDXs5).


### Book Club {#BookClub}

Book club is structured [professional development](PAG_ProfessionalDevelopment.html). The goal is to gain knowledge and insight to current projects through the perspective of someone else.

_**Spring/2023**_: We are reading _Weapons of Math Destruction: How Big Data Increases Inequality and Threatens Democracy_ by Cathy O’Neil ([Bookshop](https://bookshop.org/p/books/weapons-of-math-destruction-how-big-data-increases-inequality-and-threatens-democracy-cathy-o-neil/11438502?ean=9780553418835) |  [Amazon](https://www.amazon.com/Weapons-Math-Destruction-Increases-Inequality/dp/0553418831/ref=sr_1_1?crid=2747LPMETBAPD) | [Apple Books](https://books.apple.com/us/book/weapons-of-math-destruction-how-big-data-increases/id1605146240)) to better understand how the data, analysis, and models we create impacts others.

### Fall/2022 Meetings

  - 04/Oct/2022: How to compare Census Tract counts to Lat-Lon counts; Introduction to GitHub
  - 06/Oct/2022: Cleaning SLATE data (Emilio)
  - 11/Oct/2022: Installing and Using GitHub
  - 13/Oct/2022: Overview of the the [US Census'](https://www.census.gov/) [Geocoder](https://geocoding.geo.census.gov/geocoder/) (Steve)
  - 18/Oct/2022: Co-work session
  - 20/Oct/2022: Demonstration of kNN and Random Forest modelling in R (Seth)
  - 25/Oct/2022: Co-work session
  - 27/Oct/2022: (Social)
  - 01/Nov/2022: Co-work session
  - 03/Nov/2022: Co-work session
  - 08/Nov/2022: Co-work session
  - 10/Nov/2022: Using Google for Geocoding (Steve)
  - 15/Nov/2022: Co-work session
  - 17/Nov/2022: (Seth)
  - 22/Nov/2022:
  - 24/Nov/2022: Thanksgiving! No meeting
  - 29/Nov/2022: (Social)
  - 01/Dec/2022: (Emilio)
  - 06/Dec/2022: 
  - 08/Dec/2022: (Steve)
  - 13/Dec/2022: 
  - 15/Dec/2022: (Seth)


