---
title: "Accessing and Exploring the MSUEDW"
author: "Emilio Xavier Esposito, Ph.D."
date: "`r format(Sys.Date(), '%d/%b/%Y')`"
output: 
  rmarkdown::html_vignette
    fig_caption: yes
resource_files:
  - images_MSUEDW/*.png
vignette: >
  %\VignetteIndexEntry{Accessing and Exploring the MSUEDW}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## Accessing MSUEDW with dBeaver

[dBeaver](https://dbeaver.io) is a "free multi-platform [macOS, Windows, Linux, there is even an Eclipse plugin] database tool for developers, database administrators, analysts and all people who need to work with databases" that "supports all popular databases: MySQL, PostgreSQL, SQLite, Oracle, DB2, SQL Server, Sybase, MS Access, Teradata, Firebird, Apache Hive, Phoenix, Presto, etc."

The following

 - Visit [https://dbeaver.io](https://dbeaver.io) and click the "Download" button.
 - Install dBeaver. Please visit [https://dbeaver.io/download/](https://dbeaver.io/download/) for more information.




 
## Accessing MSUEDW Data using `R`

While the Oracle SQL Developer is a nice application for exploring the available data, why use two applications to access and analyze data?

- Install several SQL-specific R packages.

```
install.packages("DBI", "rJava", "RJDBC", "keyring", "tidyverse")
```

The `DBI`, `rJAVA`, and `RJDBC` packages allow `R` to connect to the Oracle database,
while `keyring` safely stores your password. The `tidyverse` is the g

 
 
```
options(java.parameters = c("-XX:+UseConcMarkSweepGC", "-Xmx8192m"))

library(DBI)
library(rJava)
library(RJDBC)
library(keyring)
library(tidyverse)

# Sys.setenv(JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands")

## setup keyring ----
key_set(service="MSUEDW", username="EMILIO")


## Create connection driver ----
# get JAVA drivers from https://www.oracle.com/database/technologies/jdbc-drivers-12c-downloads.html
jdbcDriver <- RJDBC::JDBC(driverClass="oracle.jdbc.OracleDriver", 
                          classPath="/Users/emilio/software/OJDBC-Full/ojdbc6.jar")


## Create connection details for MSUEDW (details are found in tnsnames.ora) ----
# Connection format is:
# jdbcConnection <- dbConnect(jdbcDriver, "jdbc:oracle:thin:@//database.hostname.com:port/service_name_or_sid", "username", "password")
# I get this looking at the tnsnames.ora 

MSUEDW.connection <- RJDBC::dbConnect(jdbcDriver, 
                                      "jdbc:oracle:thin:@//ebsprd390d.ais.msu.edu:1521/MSUEDW.EBSP.MSU.EDU",
                                      "EMILIO", 
                                      key_get("MSUEDW","EMILIO"))

## construct the SQL query ----
sql.query <- "select *
 from siscs.c_class_tbl_v
 where rownum <= 10"

## send query and fetch the results ----
query.results <- dbSendQuery(MSUEDW.connection, sql.query)
query.data <- dbFetch(query.results)
query.data

## close connection ----
dbDisconnect(MSUEDW.connection)

```
