---
title: "PAG: How I like to be Mentored"
date: "`r format(Sys.Date(), '%d/%b/%Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PAG: How I like to be Mentored}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



The "How I like to be Mentored" activity is available on [Google Docs](https://docs.google.com/document/d/1c4TzA8BWM9aRkDHFImyc8k9MbcgktBl0odh-wIpUXS0/edit?usp=sharing) for you to download (preferably as a Word document) and complete.


 - I want our working relationship to be…
 - I expect a mentor to help me with…
 - My top five priorities in life are…
 - I expect that this experience will affect my career goals by…
 - I want to learn _**[these specific skills, soft and technical]**_ from you, and here is why…
 - I can help you learn more about…
 - My top three strengths are…
 - The three things I struggle the most with are…
 - I like to work in _**[this type of working environment]**_, and this is why…
 - I prefer to have management meetings during the (select all that apply: _**morning | after lunch | afternoon**_)
 - I prefer to have group/technical meetings during the (select all that apply: _**morning | after lunch | afternoon**_)
 - I prefer to perform office-related tasks during the (select all that apply: _**early morning | mid-morning | late morning | after lunch | afternoon | evening | night**_)
 - I prefer to work on projects during the (select all that apply: _**early morning | mid-morning | late morning | after lunch | afternoon | evening | night**_)
 - My preferred communication mode is…
 - When I need technical help, I usually…
 - When I need emotional help, I usually…
 - When I am angry, I usually…
 - When I am stressed, I usually…
 - When approaching me about a concern, I want you to…
 - The best way to approach me with a concern regarding my work is...
 - The best way to approach me with a concern regarding my actions is...
 - I tend to approach others with a concern in the following manner…
 - Anything else I think is important to share:

#### Credits
 - Obtained from: [https://current.org/wp-content/uploads/2021/06/How-I-Like-to-be-supervised.pdf](https://current.org/wp-content/uploads/2021/06/How-I-Like-to-be-supervised.pdf)
 - Originally created by: [Campus Inclusion and Community, Northwestern University](https://www.northwestern.edu/inclusion/index.html) 
 - Expanded by [Emilio Xavier Esposito](https://github.com/emilioxavier)
