---
title: "Preparing for `theHUB`"
author: "Emilio Xavier Esposito, Ph.D."
date: "`r format(Sys.Date(), '%d/%b/%Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Preparing for `theHUB`}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, include=FALSE)
library(knitr)
```

# We are looking for Windows 10 and 11 beta testers!!!

---

**the Haabefuld[^1],[^2] Utility Box**_ (_**theHUB**_) was developed and designed on a Mac. theHUB _should_ work on a Windows system, but R requires a different set of applications for [macOS](https://cran.r-project.org/bin/macosx/RMacOSX-FAQ.html) versus [Windows](https://cran.r-project.org/bin/windows/base/rw-FAQ.html). Please let [Emilio](https://github.com/emilioxavier/) know if you have any trouble and he will help you out.



## Setting up R and RStudio
R and RStudio are open source and freely available applications available for numerous, popular operating systems. Specifically, RStudio is available for Windows 10, macOS 10.13+, Ubuntu 16, Ubuntu 18/Debian 10, Fedora 19/Red Hat 7, Fedora 28/Red Hat 8, Debian 9, OpenSUSE 15. 



### Installing R

Visit [CRAN](https://cran.r-project.org) and download the installer ("Precompiled binary distributions of the base system and contributed packages") for your operating system. Mac and Windows users should download the version available from CRAN. Linux users should check their distribution's package management system to see if R is available.

### Installing RStudio

- Download RStudio from the [RStudio server](https://www.rstudio.com/products/rstudio/download/).
- Double-click on the file and follow the directions for your operating system


### Installing Packages

```
install.packages("devtools", "tidyverse", "lubridate", "readxl", "openxlsx", "GGally", "tidytext", "textdata", "cowplot", "ggtext", "ragg", "ggwordcloud", "ggVennDiagram", "hexbin", "sf", "fuzzyjoin",
"zipcodeR")
```

There are several developmental packages that need to be installed from GitHub.


fix missing fonts when writing a PDF <https://github.com/thomasp85/ggraph/issues/152> extrafont::font_import() (Restart Rstudio)

extrafont::loadfonts()

### Use `ragg` with knitr

knitr supports png output from ragg by setting `dev = "ragg_png"` in the chunk settings or globally with `knitr::opts_chunk$set(dev = "ragg_png")`.
<!-- `install_github("thomasp85/ggfx")` -->

### Use `ragg` in RStudio

ragg can be used as the graphic back-end to the RStudio device (for RStudio \>= 1.4) by choosing AGG as the backend in the graphics pane in general options (see screenshot)

### Setup `zipcodeR`

```
library(zipcodeR)
download_zip_data(force = FALSE)
```


<!-- https://gadm.org/formats.html -->
<!-- https://gadm.org/download_country_v3.html -->
<!-- https://www.rspatial.org -->
<!-- download.file(url="https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_USA_gpkg.zip", -->
              <!-- destfile="~/OneDrive - Michigan State University/projects/mapfiles/gadm36_USA_gpkg.zip") -->
<!-- unzip(zipfile="~/OneDrive - Michigan State University/projects/mapfiles/gadm36_USA_gpkg.zip", -->
      <!-- exdir="~/OneDrive - Michigan State University/projects/mapfiles/") -->

<!-- mapfiles.usa <- "~/OneDrive - Michigan State University/projects/mapfiles/gadm36_USA.gpkg" -->

<!-- USA_gadm <- st_read(dsn = "gadm36_USA.gpkg", layer = "gadm36_USA_1") -->
<!-- lonlat_to_state(testPoints, states = USA_gadm, name_col = "NAME_1") -->

<!-- https://biogeo.ucdavis.edu/data/gadm3.6/Rsf/gadm36_USA_0_sf.rds -->
<!-- https://biogeo.ucdavis.edu/data/gadm3.6/Rsf/gadm36_USA_1_sf.rds -->
<!-- https://biogeo.ucdavis.edu/data/gadm3.6/Rsf/gadm36_USA_2_sf.rds -->


## OS Functions
There are two ways to install via [Homebrew](https://brew.sh/) and [MacPorts](https://www.macports.org/). According to various websites it is possible to have both Homebrew and MacPorts installed without any problems.

**Installing Homebrew** is straight forward
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Installing MacPorts** is a bit more involved and [specific install scripts are available for each macOS version](https://www.macports.org/install.php). After installing MacPorts, run the following from the macOS Terminal.
```

```



### `wget`

`wget` is a command line function to download website files. It is needed to download historical datasets and map shapefile from their respective websites.

#### macOS

[wget via Homebrew](https://formulae.brew.sh/formula/wget#default)
```
brew install wget
```

[wget via MacPorts](https://ports.macports.org/port/wget/)
```
sudo port install wget
```


#### Windows 10 & 11




## Map Shape Files
To create maps and identify country and subregions (state and county in the US) 
using location data. 

string with the path and file name of the GADM world
mapfile. Any mapfile can be used, but for datasets containing geospatial
location data from anywhere on the planet, it is advantageous to use the
entire world map. Obtain the mapfile of interest from
[https://gadm.org](https://gadm.org). The world GADM data is available from
[https://biogeo.ucdavis.edu/data/gadm3.6/gadm36_gpkg.zip](https://biogeo.ucdavis.edu/data/gadm3.6/gadm36_gpkg.zip).
Ensure the [GeoPackage format](https://gadm.org/formats.html) is downloaded.
The compressed complete world database is approximately 1.6 GBs and the
unzipped file is 3.81 GBs.

### ZIP Code Tabulation Areas 
https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html
https://www.census.gov/cgi-bin/geo/shapefiles/index.php


## Microsoft Visual Studio Code

With the [sunsetting of GitHub's Atom](https://github.blog/2022-06-08-sunsetting-atom/) the I find [Microsoft Visual Studio Code](https://code.visualstudio.com/) to be an _**excellent**_ text editor. Yes. I use, kinda like, and endorse using Microsoft Visual Studio Code. (Younger me is so disappointed.)

It has a lot of great R-related features including "syntax highlighting, R language service based on code analysis, interacting with R terminals, viewing data, plots, workspace variables, help pages, managing packages, and working with R Markdown documents" via [REditorSupport](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r)," is awesome for viewing (and sometime editing) CSV files (and other delimited files) with [Rainbow CSV](https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv), and has an [Atom teletype](https://teletype.atom.io)-like feature called [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare). Download Microsoft Visual Studio Code [here](https://code.visualstudio.com/Download).



## Footnotes

[^1]: The word haabefuld is Danish for hopeful. The **aa** is really an **å**, and thus, haabefuld is really håbefuld. The use of **aa** makes typing ([Emilio](https://github.com/emilioxavier/) can never remember the correct ASCII code for the å) and web searches easier.
[^2]: The Haabefuld Utility Box was originally _the Hub Utility Box_, _theHUB_ for short. The original name -- a [recursive backronym](https://en.wikipedia.org/wiki/Recursive_acronym) -- was a way to include The Hub for Innovation in Learning and Technology where this package's development was started. Now, _theHUB_ is used to pay homage to the Hub.
